### PR TITLE
skip broken pypy builds

### PR DESCRIPTION
**Pull request by JohannesBuchner**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by MuellerSeb** [comment]
Try `@conda-forge-admin, please rerender` as a comment here. Helped for me: https://github.com/conda-forge/gstools-feedstock/pull/11 :wink:

**Comment by JohannesBuchner** [comment]
Hmm, that didn't help unfortunately.

**Comment by MuellerSeb** [comment]
You still need to add the skip command for pypy linke here:
https://github.com/conda-forge/gstools-feedstock/blob/8b6c882aad217e68ac5c80397a99ed4238169842/recipe/meta.yaml#L13

**Comment by MuellerSeb** [comment]
@conda-forge-admin, please rerender

**Comment by JohannesBuchner** [comment]
o_O wow! it worked! Thanks @MuellerSeb

**Comment by MuellerSeb** [comment]
You are welcome! That's what a good community should do: help ;-)

**Pull request merged**
